apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
name: doppler-cluster
spec:
provider:
  doppler:
  auth:
    secretRef:
    dopplerToken:
      name: dev_token
      key: dopplerToken
      namespace: external-secrets