apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: doppler-secrets
spec:
provider:
  doppler:
    auth:
    secretRef:
      dopplerToken:
        name: eso-token-dev
        key: dopplerToken
        namespace: external-secrets