kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

generators:
  - policy-generator.yml
commonLabels:
  env: prod

patches:
  - patch: |-
      - op: replace
        path: /spec/predicates/requiredClusterSelector/matchExpressions
        value: 'dev'
    target:
      kind: Placement
      name: placement-policy-day2