apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-policy-day2
  namespace: acm-policies
spec:
  clusterSets:
  - dev
  predicates:
  - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: env
              operator: In
              values:
                - dev
