apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: day2-policy-generator


placementBindingDefaults:
  name: "day2"
policyDefaults:
  namespace: acm-policies
  remediationAction: enforce
 
policies:

  - name: policy-eso-hub
    manifests:
     - path: policies/eso/overlay/hub
    placement:
      name: placement-hub
      placementPath: placement/hub-placement.yml
 
  - name: policy-etcd-encryption
    manifests:
    - path: policies/etcd-encryption

  - name: policy-eso-dev
    manifests:
      - path: policies/eso/overlay/dev
  - name: policy-sso-dev
    manifests:
      - path: policies/sso/overlay/dev
    dependencies:
    - name: policy-eso-dev
  - name: policy-certmanager-dev
    manifests:
      - path: policies/cert-manager/base
    dependencies:
    - name: policy-eso-dev
    
policySets:
  - name: "day2-cluster-policies"
    description: "Policy for Day 2 operations"
    policies:
      - policy-eso-dev
      - policy-sso-dev
      - policy-certmanager-dev
    placement:
      name: placement-dev
      placementPath: placement/dev-placement.yml