apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: config-data-policies
policyDefaults:
  namespace: policies
  pruneObjectBehavior: "DeleteAll"
policies:
  - name: config-data
    manifests:
      - path: policy/policy-etcdencryption.yml