apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: day2-policy-generator

placementBindingDefaults:
  # Set an explicit placement binding name to use rather than rely on the default.
  name: "day2"
policyDefaults:
  namespace: acm-policies
  remediationAction: enforce
  placement:
    
  #orderManifests: true
  #consolidateManifests: false
policies:
 
  - name: policy-eso-dev
    manifests:
      - path: policies/eso/overlay/dev
  - name: policy-sso-dev
    manifests:
      - path: policies/sso/overlay/dev
    dependencies:
    - name: policy-eso-dev
    
policySets:
  - name: "day2-cluster-policies"
    description: "Policy for Day 2 operations"
    policies:
      - policy-eso-dev
      - policy-sso-dev
    placement:
      name: placement-dev
      placementPath: placement-dev.yml