apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: day2-policy-generator


placementBindingDefaults:
  name: "day2"
policyDefaults:
  namespace: acm-policies
  remediationAction: enforce
 
policies:
 
  - name: policy-etcd-encryption
    manifests:
    - path: policies/etcd-encryption

  - name: policy-eso-dev
    manifests:
      - path: policies/eso/overlay/dev
  - name: policy-sso-dev
    manifests:
      - path: policies/sso/overlay/dev
    dependencies:
    - name: policy-eso-dev
  - name: policy-certmanager-dev
    manifests:
      - path: policies/cert-manager/base
    dependencies:
    - name: policy-eso-dev
  - name: policy-acs-operator-dev
    manifests:
      - path: policies/acs/operator/overlay/dev
  - name: policy-acs-secured-cluster-dev
    manifests:
      - path: policies/acs/secured-cluster/overlay/dev
    dependencies:
    - name: policy-acs-operator-dev
    
policySets:
  - name: "day2-cluster-policies"
    description: "Policy for Day 2 operations"
    policies:
      - policy-eso-dev
      - policy-sso-dev
      - policy-certmanager-dev
      # - policy-acs-operator-dev
      # - policy-acs-secured-cluster-dev
    placement:
      name: placement-dev
      placementPath: placement-dev.yml