apiVersion: redhatcop.redhat.io/v1alpha1
kind: GroupSync
metadata:
    name: keycloak-groupsync
    namespace: group-sync-operator
spec:
    providers:
    - keycloak:
        credentialsSecret:
          kind: Secret
          name: keycloak-group-sync
          namespace: group-sync-operator
        loginRealm: policy-demo
        prune: false
        realm: policy-demo
        scope: sub
        url: 'https://lemur-10.cloud-iam.com/auth'
      name: keycloak
