apiVersion: v1
kind: Secret
metadata:
  name: oidc-secret
  namespace: openshift-config
  type: Opaque
  data:
    clientId: '{{ fromSecret "external-secrets" "all-cluster-secret" "KEYCLOAK_CLIENT_ID" | b64enc}}'
    clientSecret: '{{ fromSecret "external-secrets" "all-cluster-secret" "KEYCLOAK_CLIENT_SECRET" | b64enc}}'

