apiVersion: v1
kind: Secret
metadata:
  name: oidc-secret
  namespace: openshift-config
type: Opaque
data:
  clientSecret: '{{ fromSecret "external-secrets" "all-cluster-secret" "KEYCLOAK_CLIENT_SECRET" }}'
