apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
  ownerReferences:
    - apiVersion: config.openshift.io/v1
      kind: ClusterVersion
      name: version
spec:
  identityProviders:
    - mappingMethod: claim
      name: openid
      openID:
        claims:
          email:
            - email
          name:
            - name
          preferredUsername:
            - preferred_username
        clientID: '{{ fromSecret "external-secrets" "all-cluster-secret" "KEYCLOAK_CLIENT_ID" | base64dec}}'
        clientSecret:
          name: oidc-secret
        extraScopes: []
        issuer: 'https://lemur-10.cloud-iam.com/auth/realms/policy-demo'
      type: OpenID
