apiVersion: v1
kind: Secret
metadata:
  name: keycloak-group-sync
  namespace: group-sync-operator
  type: Opaque
  data:
    clientId: '{{ fromSecret "external-secrets" "all-cluster-secret" "KEYCLOAK_GROUP_SYNC_USERNAME" | b64enc}}'
    clientSecret: '{{ fromSecret "external-secrets" "all-cluster-secret" "KEYCLOAK_GROUP_SYNC_PASSWORD" | b64enc}}'
