apiVersion: v1
kind: Secret
metadata:
  name: keycloak-group-sync
  namespace: group-sync-operator
type: Opaque
data:
  username: '{{ fromSecret "external-secrets" "all-cluster-secret" "KEYCLOAK_GROUP_SYNC_USERNAME" }}'
  password: '{{ fromSecret "external-secrets" "all-cluster-secret" "KEYCLOAK_GROUP_SYNC_PASSWORD" }}'
