kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - namespace.yaml
  - external-secret.yaml
  - operator-groupsync.yaml
  - policy-groupsync.yaml
  - group-rolebinding.yaml

