apiVersion: v1
kind: Secret
metadata:
  name: eso-token-cluster
  namespace: external-secrets
type: Opaque
data:
  dopplerToken: '{{hub (fromSecret "external-secrets" "all-cluster-secret" (printf "DOPPLER_TOKEN_%s" upper .ManagedClusterName)) hub}}'
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: doppler-secrets
  namespace: external-secrets
spec:
  provider:
    doppler:
      auth:
        secretRef:
          dopplerToken:
            name: eso-token-cluster
            key: dopplerToken
            namespace: external-secrets
