apiVersion: v1
kind: Secret
metadata:
  name: eso-token-cluster
  namespace: external-secrets
type: Opaque
data:
  dopplerToken: '{{hub (fromSecret "acm-policies" "all-cluster-secret" (printf "DOPPLER_TOKEN_%s" (.ManagedClusterName | upper | replace "-" "_"))) hub}}'
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: doppler-secretstore
  namespace: external-secrets
  
spec:
  provider:
    doppler:
      auth:
        secretRef:
          dopplerToken:
            name: eso-token-cluster
            key: dopplerToken
