apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-secrets-operator-controller-manager
  namespace: openshift-operators
status:
  conditions:
    - status: "True"
      type: Available
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: collector
  namespace: stackrox
status:
  numberMisscheduled: 0