apiVersion: v1
kind: Secret
metadata:
  name: oidc-secret
  namespace: openshift-config
  type: Opaque
  data:
    clientSecret: {{hub (fromSecret "sso" (printf "keycloak-client-secret-ocp-%s" .ManagedClusterName ) "CLIENT_SECRET") | b64enc hub}}