apiVersion: v1
kind: Secret
metadata:
  name: aws-route53-creds
  namespace: cert-manager-operator 
type: Opaque
data:
  awsSecretAccessKey: '{{ fromSecret "external-secrets" "all-cluster-secret" "CERTMANAGER_AWS_SECRET_ACCESS_KEY" }}'
