apiVersion: v1
kind: Secret
metadata:
  name: aws-route53-creds
  namespace: cert-manager 
type: Opaque
data:
  awsSecretAccessKey: '{{ fromSecret "external-secrets" "all-cluster-secret" "CERTMANAGER_AWS_SECRET_ACCESS_KEY" }}'
  awsAccessKey: '{{ fromSecret "external-secrets" "all-cluster-secret" "CERTMANAGER_AWS_ACCESS_KEY" }}'