apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: enable-etcd-encryption
spec:
  remediationAction: enforce
  severity: low
  object-templates:
    - complianceType: musthave
      objectDefinition:
        apiVersion: config.openshift.io/v1
        kind: APIServer
        metadata:
          name: cluster
        spec:
          encryption:
            type: aescbc
---
apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: enable-etcd-encryption-status-kubeapi
spec:
  remediationAction: inform
  severity: low
  object-templates:
    - complianceType: musthave
      objectDefinition:
        apiVersion: operator.openshift.io/v1
        kind: KubeAPIServer
        metadata:
          name: cluster
        status:
          conditions:
            - message: 'All resources encrypted: secrets, configmaps'
              reason: EncryptionCompleted