apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: doppler-secretstore
  namespace: acm-policies
spec:
  provider:
    doppler:
      auth:
        secretRef:
          dopplerToken:
            name: eso-token
            key: dopplerToken
