apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: all-cluster-secret
  namespace: acm-policies
spec:
  refreshInterval: "1h"
  secretStoreRef:
    kind: SecretStore
    name: doppler-secretstore

  target:
    name: all-cluster-secret

  dataFrom:
    - find:
        name:
          regexp: .*

